### ISSUE TITLE
onTempChangeListener回调的change事件不设置的时候会报错

### ISSUE THREAD

**Issue by beau2012** [alidili/TempControlView#1]
case MotionEvent.ACTION_UP: {
                if (isDown && isMove) {
                    // 纠正指针位置
                    rotateAngle = (float) ((temperature - minTemp) * angleRate * angleOne);
                    invalidate();
                    // 回调温度改变监听
                    onTempChangeListener.change(temperature);
                    isDown = false;
                    isMove = false;
                }
                break;
            }
这个  onTempChangeListener.change(temperature);地方好像应该判断onTempChangeListener是否为null不然不设置onTempChangeListener会报null指针异常

**Comment by alidili** [comment]
多谢大侠提醒，我这就去加上判断 @yourbelief
